In [1]:
import pandas as pd
from arcgis import GIS
gis = GIS()
from arcgis.features import FeatureLayer
import requests
import arcpy
import _config
import importlib
importlib.reload(_config)
import os

In [2]:
strRelease = "WF TDM v9.0.1"
lstFieldsFromForecasts = ['SEGID','MF2023','MF2028','MF2032','MF2042','MF2050','ADJ2023','ADJ2028','ADJ2032','ADJ2042','ADJ2050','ADJHIST']

In [3]:
# read segments
sdfSegments = pd.DataFrame.spatial.from_featureclass(('intermediate/'+ os.path.splitext(os.path.basename(_config.fnWfSegments))[0]+ '_GeoKeys_AADTs_Factors.shp'))
display(sdfSegments)

,FID,Id,SEGID,BMP,EMP,DISTANCE,CO_FIPS,ROUTE,SUBAREAID,PLANAREA,...,FAC_SUM,FAC_SUN,FAC_THU,FAC_TUE,FAC_WDAVG,FAC_WEAVG,FAC_WED,FAC_WEMAX,FAC_WIN,SHAPE
0,0,0,0006_141.0,141.035,146.868,5.843301,49.0,0006,1.0,MAG,...,1.0914,0.8819,1.0120,0.9628,0.9840,0.9734,0.9773,1.0649,0.8495,"{""paths"": [[[405824.11000000034, 4423860.33], ..."
1,1,0,0006_146.9,146.868,149.902,3.039023,49.0,0006,1.0,MAG,...,1.0914,0.8819,1.0120,0.9628,0.9840,0.9734,0.9773,1.0649,0.8495,"{""paths"": [[[413442.55030000024, 4422753.7282]..."
2,2,0,0006_149.9,149.902,150.580,0.677983,49.0,0006,1.0,MAG,...,1.0914,0.8819,1.0120,0.9628,0.9840,0.9734,0.9773,1.0649,0.8495,"{""paths"": [[[418330.7999999998, 4422866], [418..."
3,3,0,0006_150.6,150.580,152.555,1.973104,49.0,0006,1.0,MAG,...,1.0914,0.8819,1.0120,0.9628,0.9840,0.9734,0.9773,1.0649,0.8495,"{""paths"": [[[419421.8803000003, 4422872.2963],..."
4,4,0,0006_152.6,152.555,152.871,0.316275,49.0,0006,1.0,MAG,...,1.0914,0.8819,1.0120,0.9628,0.9840,0.9734,0.9773,1.0649,0.8495,"{""paths"": [[[422596.89969999995, 4422889.2949]..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5475,5475,0,WFRC_8489,0.000,0.000,0.505514,35.0,WFRC,1.0,WFRC,...,1.0283,0.6061,1.1071,1.0813,1.0924,0.7653,1.0887,0.9245,0.9370,"{""paths"": [[[420577.9068, 4495035.7042], [4205..."
5476,5476,0,WFRC_8490,0.000,0.000,0.737896,35.0,WFRC,1.0,WFRC,...,1.0283,0.6061,1.1071,1.0813,1.0924,0.7653,1.0887,0.9245,0.9370,"{""paths"": [[[421385.5, 4495026.199999999], [42..."
5477,5477,0,WFRC_8491,0.000,0.000,0.265495,35.0,WFRC,1.0,WFRC,...,1.0283,0.6061,1.1071,1.0813,1.0924,0.7653,1.0887,0.9245,0.9370,"{""paths"": [[[422563.71669999976, 4495144.5842]..."
5478,5478,0,WFRC_8492,0.000,0.000,0.444725,35.0,WFRC,1.0,WFRC,...,1.0135,0.6293,1.1063,1.0851,1.0946,0.7583,1.0925,0.8873,0.9653,"{""paths"": [[[423341.02249999996, 4513066.2261]..."
5479,5479,0,WFRC_8493,0.000,0.000,0.583552,35.0,WFRC,1.0,WFRC,...,1.0283,0.6061,1.1071,1.0813,1.0924,0.7653,1.0887,0.9245,0.9370,"{""paths"": [[[417222.4900000002, 4482555.470000..."

In [4]:
# Connect to GIS
gis = GIS()

# Access the feature layer
feature_layer_url = 'https://services1.arcgis.com/taguadKoI1XFwivx/arcgis/rest/services/ForecastsWFRCFinal_gdb/FeatureServer/0'
feature_layer = FeatureLayer(feature_layer_url)

# Convert to Spatially Enabled DataFrame
sdfForecasts = feature_layer.query().sdf
sdfForecasts = sdfForecasts[lstFieldsFromForecasts] # filter columns by list

display(sdfForecasts)

,SEGID,MF2023,MF2028,MF2032,MF2042,MF2050,ADJ2023,ADJ2028,ADJ2032,ADJ2042,ADJ2050,ADJHIST
0,0006_141.0,1600.0,1700.0,1800.0,2100.0,2400.0,0.0,100.0,0.0,0.0,0.0,0.0
1,0006_146.9,1700.0,1700.0,1900.0,2100.0,2400.0,0.0,100.0,0.0,0.0,0.0,0.0
2,0006_149.9,2600.0,2900.0,2900.0,3500.0,6100.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0006_150.6,2600.0,2900.0,3000.0,3600.0,6200.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0006_152.6,2500.0,2900.0,2900.0,3500.0,5900.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4975,WFRC_8469,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4976,WFRC_8470,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4977,WFRC_8471,0.0,0.0,13500.0,16500.0,18500.0,0.0,0.0,0.0,0.0,0.0,0.0
4978,WFRC_8472,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4979,WFRC_8473,6400.0,6400.0,6800.0,7500.0,8300.0,500.0,0.0,0.0,0.0,0.0,0.0

In [5]:
years = [2023, 2028, 2032, 2042, 2050]

for year in years:
    # F  : Forecast 
    # MF : Model Forecast (model volume + base year adjustment)
    # ADJ: Manual Adjustment
    sdfForecasts[f'F{year}'] = sdfForecasts[f'MF{year}'] + sdfForecasts[f'ADJ{year}'] + sdfForecasts['ADJHIST']

sdfForecasts

,SEGID,MF2023,MF2028,MF2032,MF2042,MF2050,ADJ2023,ADJ2028,ADJ2032,ADJ2042,ADJ2050,ADJHIST,F2023,F2028,F2032,F2042,F2050
0,0006_141.0,1600.0,1700.0,1800.0,2100.0,2400.0,0.0,100.0,0.0,0.0,0.0,0.0,1600.0,1800.0,1800.0,2100.0,2400.0
1,0006_146.9,1700.0,1700.0,1900.0,2100.0,2400.0,0.0,100.0,0.0,0.0,0.0,0.0,1700.0,1800.0,1900.0,2100.0,2400.0
2,0006_149.9,2600.0,2900.0,2900.0,3500.0,6100.0,0.0,0.0,0.0,0.0,0.0,0.0,2600.0,2900.0,2900.0,3500.0,6100.0
3,0006_150.6,2600.0,2900.0,3000.0,3600.0,6200.0,0.0,0.0,0.0,0.0,0.0,0.0,2600.0,2900.0,3000.0,3600.0,6200.0
4,0006_152.6,2500.0,2900.0,2900.0,3500.0,5900.0,0.0,0.0,0.0,0.0,0.0,0.0,2500.0,2900.0,2900.0,3500.0,5900.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4975,WFRC_8469,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4976,WFRC_8470,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4977,WFRC_8471,0.0,0.0,13500.0,16500.0,18500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13500.0,16500.0,18500.0
4978,WFRC_8472,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4979,WFRC_8473,6400.0,6400.0,6800.0,7500.0,8300.0,500.0,0.0,0.0,0.0,0.0,0.0,6900.0,6400.0,6800.0,7500.0,8300.0

In [6]:
sdfForecasts.columns

Index(['SEGID', 'MF2023', 'MF2028', 'MF2032', 'MF2042', 'MF2050', 'ADJ2023',
       'ADJ2028', 'ADJ2032', 'ADJ2042', 'ADJ2050', 'ADJHIST', 'F2023', 'F2028',
       'F2032', 'F2042', 'F2050'],
      dtype='object')

In [7]:
sdfForecastsPlusSegments = pd.merge(sdfForecasts,sdfSegments,on='SEGID',how='right')
sdfForecastsPlusSegments.fillna(0,inplace=True)
sdfForecastsPlusSegments

,SEGID,MF2023,MF2028,MF2032,MF2042,MF2050,ADJ2023,ADJ2028,ADJ2032,ADJ2042,...,FAC_SUM,FAC_SUN,FAC_THU,FAC_TUE,FAC_WDAVG,FAC_WEAVG,FAC_WED,FAC_WEMAX,FAC_WIN,SHAPE
0,0006_141.0,1600.0,1700.0,1800.0,2100.0,2400.0,0.0,100.0,0.0,0.0,...,1.0914,0.8819,1.0120,0.9628,0.9840,0.9734,0.9773,1.0649,0.8495,"{'paths': [[[405824.11000000034, 4423860.33], ..."
1,0006_146.9,1700.0,1700.0,1900.0,2100.0,2400.0,0.0,100.0,0.0,0.0,...,1.0914,0.8819,1.0120,0.9628,0.9840,0.9734,0.9773,1.0649,0.8495,"{'paths': [[[413442.55030000024, 4422753.7282]..."
2,0006_149.9,2600.0,2900.0,2900.0,3500.0,6100.0,0.0,0.0,0.0,0.0,...,1.0914,0.8819,1.0120,0.9628,0.9840,0.9734,0.9773,1.0649,0.8495,"{'paths': [[[418330.7999999998, 4422866], [418..."
3,0006_150.6,2600.0,2900.0,3000.0,3600.0,6200.0,0.0,0.0,0.0,0.0,...,1.0914,0.8819,1.0120,0.9628,0.9840,0.9734,0.9773,1.0649,0.8495,"{'paths': [[[419421.8803000003, 4422872.2963],..."
4,0006_152.6,2500.0,2900.0,2900.0,3500.0,5900.0,0.0,0.0,0.0,0.0,...,1.0914,0.8819,1.0120,0.9628,0.9840,0.9734,0.9773,1.0649,0.8495,"{'paths': [[[422596.89969999995, 4422889.2949]..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5475,WFRC_8489,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0283,0.6061,1.1071,1.0813,1.0924,0.7653,1.0887,0.9245,0.9370,"{'paths': [[[420577.9068, 4495035.7042], [4205..."
5476,WFRC_8490,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0283,0.6061,1.1071,1.0813,1.0924,0.7653,1.0887,0.9245,0.9370,"{'paths': [[[421385.5, 4495026.199999999], [42..."
5477,WFRC_8491,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0283,0.6061,1.1071,1.0813,1.0924,0.7653,1.0887,0.9245,0.9370,"{'paths': [[[422563.71669999976, 4495144.5842]..."
5478,WFRC_8492,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0135,0.6293,1.1063,1.0851,1.0946,0.7583,1.0925,0.8873,0.9653,"{'paths': [[[423341.02249999996, 4513066.2261]..."
5479,WFRC_8493,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0283,0.6061,1.1071,1.0813,1.0924,0.7653,1.0887,0.9245,0.9370,"{'paths': [[[417222.4900000002, 4482555.470000..."

In [8]:
# cacluate and adjusted base year
sdfForecastsPlusSegments['F2019'] = sdfForecastsPlusSegments['AADT2019'] + sdfForecastsPlusSegments['ADJHIST']

In [9]:
# calculate change fields
periods = [
    ('19TO50', 'F2019', 'F2050'),
    ('19TO23', 'F2019', 'F2023'),
    ('23TO28', 'F2023', 'F2028'),
    ('28TO32', 'F2028', 'F2032'),
    ('32TO42', 'F2032', 'F2042'),
    ('42TO50', 'F2042', 'F2050')
]

for period, start_year_key, end_year_key in periods:
    ch_key = f'CH{period}'
    sdfForecastsPlusSegments[ch_key] = sdfForecastsPlusSegments[end_year_key] - sdfForecastsPlusSegments[start_year_key]

sdfForecastsPlusSegments

,SEGID,MF2023,MF2028,MF2032,MF2042,MF2050,ADJ2023,ADJ2028,ADJ2032,ADJ2042,...,FAC_WEMAX,FAC_WIN,SHAPE,F2019,CH19TO50,CH19TO23,CH23TO28,CH28TO32,CH32TO42,CH42TO50
0,0006_141.0,1600.0,1700.0,1800.0,2100.0,2400.0,0.0,100.0,0.0,0.0,...,1.0649,0.8495,"{'paths': [[[405824.11000000034, 4423860.33], ...",1517.0,883.0,83.0,200.0,0.0,300.0,300.0
1,0006_146.9,1700.0,1700.0,1900.0,2100.0,2400.0,0.0,100.0,0.0,0.0,...,1.0649,0.8495,"{'paths': [[[413442.55030000024, 4422753.7282]...",1517.0,883.0,183.0,100.0,100.0,200.0,300.0
2,0006_149.9,2600.0,2900.0,2900.0,3500.0,6100.0,0.0,0.0,0.0,0.0,...,1.0649,0.8495,"{'paths': [[[418330.7999999998, 4422866], [418...",2441.0,3659.0,159.0,300.0,0.0,600.0,2600.0
3,0006_150.6,2600.0,2900.0,3000.0,3600.0,6200.0,0.0,0.0,0.0,0.0,...,1.0649,0.8495,"{'paths': [[[419421.8803000003, 4422872.2963],...",2441.0,3759.0,159.0,300.0,100.0,600.0,2600.0
4,0006_152.6,2500.0,2900.0,2900.0,3500.0,5900.0,0.0,0.0,0.0,0.0,...,1.0649,0.8495,"{'paths': [[[422596.89969999995, 4422889.2949]...",2417.0,3483.0,83.0,400.0,0.0,600.0,2400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5475,WFRC_8489,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.9245,0.9370,"{'paths': [[[420577.9068, 4495035.7042], [4205...",0.0,0.0,0.0,0.0,0.0,0.0,0.0
5476,WFRC_8490,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.9245,0.9370,"{'paths': [[[421385.5, 4495026.199999999], [42...",0.0,0.0,0.0,0.0,0.0,0.0,0.0
5477,WFRC_8491,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.9245,0.9370,"{'paths': [[[422563.71669999976, 4495144.5842]...",0.0,0.0,0.0,0.0,0.0,0.0,0.0
5478,WFRC_8492,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.8873,0.9653,"{'paths': [[[423341.02249999996, 4513066.2261]...",0.0,0.0,0.0,0.0,0.0,0.0,0.0
5479,WFRC_8493,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.9245,0.9370,"{'paths': [[[417222.4900000002, 4482555.470000...",0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
lstDropFields = [item for item in lstFieldsFromForecasts if item != 'SEGID']
sdfForecastsPlusSegments.drop(columns=lstDropFields, inplace=True)
sdfForecastsPlusSegments

,SEGID,F2023,F2028,F2032,F2042,F2050,FID,Id,BMP,EMP,...,FAC_WEMAX,FAC_WIN,SHAPE,F2019,CH19TO50,CH19TO23,CH23TO28,CH28TO32,CH32TO42,CH42TO50
0,0006_141.0,1600.0,1800.0,1800.0,2100.0,2400.0,0,0,141.035,146.868,...,1.0649,0.8495,"{'paths': [[[405824.11000000034, 4423860.33], ...",1517.0,883.0,83.0,200.0,0.0,300.0,300.0
1,0006_146.9,1700.0,1800.0,1900.0,2100.0,2400.0,1,0,146.868,149.902,...,1.0649,0.8495,"{'paths': [[[413442.55030000024, 4422753.7282]...",1517.0,883.0,183.0,100.0,100.0,200.0,300.0
2,0006_149.9,2600.0,2900.0,2900.0,3500.0,6100.0,2,0,149.902,150.580,...,1.0649,0.8495,"{'paths': [[[418330.7999999998, 4422866], [418...",2441.0,3659.0,159.0,300.0,0.0,600.0,2600.0
3,0006_150.6,2600.0,2900.0,3000.0,3600.0,6200.0,3,0,150.580,152.555,...,1.0649,0.8495,"{'paths': [[[419421.8803000003, 4422872.2963],...",2441.0,3759.0,159.0,300.0,100.0,600.0,2600.0
4,0006_152.6,2500.0,2900.0,2900.0,3500.0,5900.0,4,0,152.555,152.871,...,1.0649,0.8495,"{'paths': [[[422596.89969999995, 4422889.2949]...",2417.0,3483.0,83.0,400.0,0.0,600.0,2400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5475,WFRC_8489,0.0,0.0,0.0,0.0,0.0,5475,0,0.000,0.000,...,0.9245,0.9370,"{'paths': [[[420577.9068, 4495035.7042], [4205...",0.0,0.0,0.0,0.0,0.0,0.0,0.0
5476,WFRC_8490,0.0,0.0,0.0,0.0,0.0,5476,0,0.000,0.000,...,0.9245,0.9370,"{'paths': [[[421385.5, 4495026.199999999], [42...",0.0,0.0,0.0,0.0,0.0,0.0,0.0
5477,WFRC_8491,0.0,0.0,0.0,0.0,0.0,5477,0,0.000,0.000,...,0.9245,0.9370,"{'paths': [[[422563.71669999976, 4495144.5842]...",0.0,0.0,0.0,0.0,0.0,0.0,0.0
5478,WFRC_8492,0.0,0.0,0.0,0.0,0.0,5478,0,0.000,0.000,...,0.8873,0.9653,"{'paths': [[[423341.02249999996, 4513066.2261]...",0.0,0.0,0.0,0.0,0.0,0.0,0.0
5479,WFRC_8493,0.0,0.0,0.0,0.0,0.0,5479,0,0.000,0.000,...,0.9245,0.9370,"{'paths': [[[417222.4900000002, 4482555.470000...",0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
sdfForecastsPlusSegments.columns


# Set display options to ensure no truncation
pd.set_option('display.max_columns', None)  # Ensures all columns are shown
pd.set_option('display.max_seq_items', None)  # For potentially long sequences

# Now, when you print or display the DataFrame, all column names will be shown
print(sdfForecastsPlusSegments.columns)

# Reset display options to default
pd.reset_option('display.max_columns')
pd.reset_option('display.max_seq_items')

Index(['SEGID', 'F2023', 'F2028', 'F2032', 'F2042', 'F2050', 'FID', 'Id',
       'BMP', 'EMP', 'DISTANCE', 'CO_FIPS', 'ROUTE', 'SUBAREAID', 'PLANAREA',
       'DIRECTION', 'AADTSTN', 'Section_Le', 'AADT2023', 'AADT2022',
       'AADT2021', 'AADT2020', 'AADT2019', 'AADT2018', 'AADT2017', 'AADT2016',
       'AADT2015', 'AADT2014', 'AADT2013', 'AADT2012', 'AADT2011', 'AADT2010',
       'AADT2009', 'AADT2008', 'AADT2007', 'AADT2006', 'AADT2005', 'AADT2004',
       'AADT2003', 'AADT2002', 'AADT2001', 'AADT2000', 'AADT1999', 'AADT1998',
       'AADT1997', 'AADT1996', 'AADT1995', 'AADT1994', 'AADT1993', 'AADT1992',
       'AADT1991', 'AADT1990', 'AADT1989', 'AADT1988', 'AADT1987', 'AADT1986',
       'AADT1985', 'AADT1984', 'AADT1983', 'AADT1982', 'AADT1981', 'SUTRK2023',
       'CUTRK2023', 'SUTRK2022', 'CUTRK2022', 'SUTRK2021', 'CUTRK2021',
       'SUTRK2020', 'CUTRK2020', 'SUTRK2019', 'CUTRK2019', 'SUTRK2018',
       'CUTRK2018', 'SUTRK2017', 'CUTRK2017', 'SUTRK2016', 'CUTRK2016',
       'SUTRK2015', 'CUTRK2015', 'SUTRK2014', 'CUTRK2014', 'SUTRK2013',
       'CUTRK2013', 'SUTRK2012', 'CUTRK2012', 'SUTRK2011', 'CUTRK2011',
       'SUTRK2010', 'CUTRK2010', 'Shape__Len', 'CCSGROUP19', 'FACMANADJ',
       'FAC_APR', 'FAC_AUG', 'FAC_DEC', 'FAC_FAL', 'FAC_FEB', 'FAC_FRI',
       'FAC_JAN', 'FAC_JUL', 'FAC_JUN', 'FAC_MAR', 'FAC_MAX', 'FAC_MAXMO',
       'FAC_MAY', 'FAC_MON', 'FAC_NOV', 'FAC_OCT', 'FAC_SAT', 'FAC_SEP',
       'FAC_SPR', 'FAC_SUM', 'FAC_SUN', 'FAC_THU', 'FAC_TUE', 'FAC_WDAVG',
       'FAC_WEAVG', 'FAC_WED', 'FAC_WEMAX', 'FAC_WIN', 'SHAPE', 'F2019',
       'CH19TO50', 'CH19TO23', 'CH23TO28', 'CH28TO32', 'CH32TO42', 'CH42TO50'],
      dtype='object')

In [15]:
lstFinalCols = ['SEGID',
                'ROUTE', 'BMP', 'EMP', 'DISTANCE', 'DIRECTION', 'CO_FIPS', 'SUBAREAID', 'PLANAREA',
                'F2019', 'F2023', 'F2028', 'F2032', 'F2042', 'F2050',
                'CH19TO50', 'CH19TO23', 'CH23TO28', 'CH28TO32', 'CH32TO42', 'CH42TO50', 
                'AADTSTN',
                'AADT2022', 'AADT2021', 'AADT2020', 'AADT2019', 'AADT2018', 'AADT2017',
                'AADT2016', 'AADT2015', 'AADT2014', 'AADT2013', 'AADT2012', 'AADT2011',
                'AADT2010', 'AADT2009', 'AADT2008', 'AADT2007', 'AADT2006', 'AADT2005',
                'AADT2004', 'AADT2003', 'AADT2002', 'AADT2001', 'AADT2000', 'AADT1999',
                'AADT1998', 'AADT1997', 'AADT1996', 'AADT1995', 'AADT1994', 'AADT1993',
                'AADT1992', 'AADT1991', 'AADT1990', 'AADT1989', 'AADT1988', 'AADT1987',
                'AADT1986', 'AADT1985', 'AADT1984', 'AADT1983', 'AADT1982', 'AADT1981',
                'SUTRK2022', 'CUTRK2022', 'SUTRK2021', 'CUTRK2021', 'SUTRK2020',
                'CUTRK2020', 'SUTRK2019', 'CUTRK2019', 'SUTRK2018', 'CUTRK2018',
                'SUTRK2017', 'CUTRK2017', 'SUTRK2016', 'CUTRK2016', 'SUTRK2015',
                'CUTRK2015', 'SUTRK2014', 'CUTRK2014', 'SUTRK2013', 'CUTRK2013',
                'SUTRK2012', 'CUTRK2012', 'SUTRK2011', 'CUTRK2011', 'SUTRK2010',
                'CUTRK2010', 'CCSGROUP19',
                'FAC_WDAVG', 'FAC_WEAVG', 'FAC_WEMAX',
                'FAC_MON', 'FAC_TUE', 'FAC_WED', 'FAC_THU', 'FAC_FRI', 'FAC_SAT', 'FAC_SUN',
                'FAC_SPR', 'FAC_SUM', 'FAC_FAL', 'FAC_WIN', 
                'FAC_JAN', 'FAC_FEB', 'FAC_MAR', 'FAC_APR', 'FAC_MAY', 'FAC_JUN',
                'FAC_JUL', 'FAC_AUG', 'FAC_SEP', 'FAC_OCT', 'FAC_NOV', 'FAC_DEC',
                'FAC_MAXMO','FAC_MAX',  
                'FACMANADJ', 'SHAPE']


sdfForecastsPlusSegmentsFinal = sdfForecastsPlusSegments[lstFinalCols].copy()
sdfForecastsPlusSegmentsFinal

,SEGID,ROUTE,BMP,EMP,DISTANCE,DIRECTION,CO_FIPS,SUBAREAID,PLANAREA,F2019,...,FAC_JUL,FAC_AUG,FAC_SEP,FAC_OCT,FAC_NOV,FAC_DEC,FAC_MAXMO,FAC_MAX,FACMANADJ,SHAPE
0,0006_141.0,0006,141.035,146.868,5.843301,EB/WB,49.0,1.0,MAG,1517.0,...,1.0796,1.0897,1.0752,1.0684,0.9511,0.8822,5,1.1065,0.0,"{'paths': [[[405824.11000000034, 4423860.33], ..."
1,0006_146.9,0006,146.868,149.902,3.039023,EB/WB,49.0,1.0,MAG,1517.0,...,1.0796,1.0897,1.0752,1.0684,0.9511,0.8822,5,1.1065,0.0,"{'paths': [[[413442.55030000024, 4422753.7282]..."
2,0006_149.9,0006,149.902,150.580,0.677983,EB/WB,49.0,1.0,MAG,2441.0,...,1.0796,1.0897,1.0752,1.0684,0.9511,0.8822,5,1.1065,0.0,"{'paths': [[[418330.7999999998, 4422866], [418..."
3,0006_150.6,0006,150.580,152.555,1.973104,EB/WB,49.0,1.0,MAG,2441.0,...,1.0796,1.0897,1.0752,1.0684,0.9511,0.8822,5,1.1065,0.0,"{'paths': [[[419421.8803000003, 4422872.2963],..."
4,0006_152.6,0006,152.555,152.871,0.316275,EB/WB,49.0,1.0,MAG,2417.0,...,1.0796,1.0897,1.0752,1.0684,0.9511,0.8822,5,1.1065,0.0,"{'paths': [[[422596.89969999995, 4422889.2949]..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5475,WFRC_8489,WFRC,0.000,0.000,0.505514,EB/WB,35.0,1.0,WFRC,0.0,...,1.0100,1.0396,1.0434,1.0358,0.9936,0.9616,9,1.0434,0.0,"{'paths': [[[420577.9068, 4495035.7042], [4205..."
5476,WFRC_8490,WFRC,0.000,0.000,0.737896,EB/WB,35.0,1.0,WFRC,0.0,...,1.0100,1.0396,1.0434,1.0358,0.9936,0.9616,9,1.0434,0.0,"{'paths': [[[421385.5, 4495026.199999999], [42..."
5477,WFRC_8491,WFRC,0.000,0.000,0.265495,EB/WB,35.0,1.0,WFRC,0.0,...,1.0100,1.0396,1.0434,1.0358,0.9936,0.9616,9,1.0434,0.0,"{'paths': [[[422563.71669999976, 4495144.5842]..."
5478,WFRC_8492,WFRC,0.000,0.000,0.444725,NB/SB,35.0,1.0,WFRC,0.0,...,0.9960,1.0223,1.0238,1.0103,0.9944,0.9907,5,1.0245,0.0,"{'paths': [[[423341.02249999996, 4513066.2261]..."
5479,WFRC_8493,WFRC,0.000,0.000,0.583552,EB/WB,35.0,1.0,WFRC,0.0,...,1.0100,1.0396,1.0434,1.0358,0.9936,0.9616,9,1.0434,0.0,"{'paths': [[[417222.4900000002, 4482555.470000..."

In [16]:
# EXPORT FOR TDM
# use '_Draft' or '_Final'
sdfForecastsPlusSegmentsFinal.spatial.to_featureclass('results/' + os.path.splitext(os.path.basename(_config.fnWfSegments))[0] + '.shp',sanitize_columns=False)

'd:\\GitHub\\WF-TDM-v9x\\1_Inputs\\6_Segment\\_Segment Processing Tools\\results\\WFv910_Segments.shp'